---
title: "Tutorial9"
author: "Anh Thu Kieu"
date: "2023-05-04"
output: html_document
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = "center",
                      fig.path = "Figures/")
```

=======
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
data <- read_csv(here::here("Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019 (2).csv"))
```

# Section 4
```{r}
data <- data %>% 
  filter(`Offence Subgroup` == 'B41 Motor vehicle theft')
```

```{r}
library(tidyverse)
library(dplyr)
library(here)
```

```{r}
accident <-  read_csv(here::here('Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019 (2).csv'))

## R Markdown

```

```{r crime}
crime <- read_csv(here::here("Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019 (2).csv"))


```

```{r}
accidentfilter <- accident %>%
  filter(`Offence Subdivision` == "B40 Theft")


ggplot(data = accidentfilter, aes(x=Year, y=`Incidents Recorded`)) +
  geom_point()

```

```

```{r}

ggplot(data = data, aes(x = Year, y = Incidents_Recorded)) +
  geom_line() +
  geom_point()
```

The graph is interesting.


```{r driving-plot, echo=FALSE}
dgr_driving <- crime %>% filter(`Offence Subgroup` == "A81 Dangerous driving") 


dgr_driving %>% 
  mutate(Year = as.factor(Year)) %>%
  ggplot() + 
  geom_col(aes(x = Year, y = `Incidents Recorded`))

```

